main = ".worker-next/index.mjs"
name = "portfolio-site-v2"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-24"
compatibility_flags = ["nodejs_compat"]
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }
